# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f57b0bec8c8b215352eef891e246c20f698f2d4afa4f4bed818a5826ee85361390d2564a2b5cf332fa5f2f1a58aa80d9d89ef8829942f9676f5bc6c0f9330bfe

test:
  secret_key_base: 99cf76ae277de939bea8b46fa345de989f05f70cf612dbbeff7d7124508043fb5f663eb712f2b13881cfaf71293d1dafd56cd14248352c6eb5caf735c149c123

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
